"""Added point value

Revision ID: 00552f3be6bf
Revises: 38ad8e3e6aee
Create Date: 2025-09-29 06:14:10.923954

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '00552f3be6bf'
down_revision: Union[str, Sequence[str], None] = '38ad8e3e6aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('point_value', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'point_value')
    # ### end Alembic commands ###
