"""Add users table

Revision ID: 89f2d9a6ca5e
Revises: 84d99442d033
Create Date: 2025-08-26 23:25:03.313181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '89f2d9a6ca5e'
down_revision: Union[str, Sequence[str], None] = '84d99442d033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('google_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
